### ISSUE TITLE
Keeps in "Loading" if the shortcut is changed

### ISSUE THREAD

**Issue by matog** [CeroProgramming/ulauncher-pulsecontrol#2]
I've changed the shortcut to "vol".
After typing the shortcut to access "Volume extension", it keeps showing "Loading..." beside de Volume extension icon. 
(Ubuntu 20.04).
The same with "device" changed for "dev"
With shortcuts "volume" and "devices" it works ok.

**Comment by CeroProgramming** [comment]
Hi, thanks for the report. 
Forgot to implement this path. I just patched the code, so hopefully, everything works if you update to the latest version. :smile: 

Regards, Simon

**Comment by matog** [comment]
Works! Thanks!
