### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by ragusa87** [CeroProgramming/ulauncher-pulsecontrol#3]
Hello,

When I try to change the volume (or any other action), nothing happen and ulauncher displays a "Loading.." message.

I ran ulauncher with the `--dev` flag but I got no related output or crash.

Running the following command works fine from a terminal:
> pactl set-sink-volume @DEFAULT_SINK@ -20%

Maybe you should adapt your script to use @DEFAULT_SINK@ instead of parsing the sink list from pactl ?
You could also use the "short" keyword to have a smaller and easier output to parse:

> pactl list short sinks
`1	alsa_output.pci-0000_00_1b.0.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING`

> pacmd list-sinks | grep index
`  * index: 1`

Versions:
```
ulauncher-pulsecontrol@31c9dd2ba8471ee59f51bd4a35597965431c79d9
ulauncher 5.7.5
pactl 13.99.1
```

Thanks for your help.

**Comment by CeroProgramming** [comment]
Hi! Thanks for the report. Sorry for the late response, I was a bit busy lately. The change you proposed seems to work, so I adopted it in the latest commit. If there are any more problems let me now.
Have a nice day and stay healthy!

**Comment by ragusa87** [comment]
Thanks a lot for your work, it works !
