### ISSUE TITLE
LOGGER in main.py is not defined

### ISSUE THREAD

**Issue by dhelmr** [CeroProgramming/ulauncher-pulsecontrol#4]
Hi, I tried the extension, but it did not work at first. I then investigated the code a bit and noticed that `LOGGER` referenced [here](https://github.com/CeroProgramming/ulauncher-pulsecontrol/blob/master/main.py#L23) is not defined in the code, probably causing the extension to terminate there. Removing the line makes the extension to work as expected.

**Comment by CeroProgramming** [comment]
Hi, thanks for the report! You are right, it should have been in a commit which is dev-branch only but it looks like I added the line to the wrong commit. It is removed now. 
Have a nice day and stay healthy!
