### ISSUE TITLE
Pipewire Support

### ISSUE THREAD

**Issue by ZXSwire3** [CeroProgramming/ulauncher-pulsecontrol#7]
This extension was really useful to have to change audio devices for me, ans I was wondering if it would be possible to add support for pipewire. Honestly I don't know if it would be a simple change or not, but I just know that when I run 
>pactl info

it says it's running PulseAudio (on PipeWire). It would just be a nice addition to have.

**Comment by YetAnotherSimon** [comment]
@ZXSwire3 Since I switched to pipewire a few weeks ago, I took the time to implement this feature (and also improve the structure of the code). If you still like to test it, you are very welcome to report if it works fine.
